services:
  - type: web
    name: token-engine-api
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: COBO_API_PUBLIC_KEY
        sync: false
      - key: COBO_API_PRIVATE_KEY
        sync: false
      - key: COBO_API_URL
        value: https://api.cobo.com/v2
      - key: CHAIN_ID
        value: MATIC_POLYGON
      - key: COBO_DEFAULT_WALLET_ID
        sync: false
